version: "2.1"
services:
  app:
    build: ./app
    image: ageapps/docker-chat:app
    ports:
      - "8080:5000"
    volumes:
      - ./app:/app # volume in host -> $(pwd)/database
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=docker-chat:*
      - MONGO_USERNAME=node
      - MONGO_PASSWORD=node
      - MONGO_DATABASE=nodedb
      - PORT=5000
      # - RABBIT_HOST=rabbit
    command: [nodemon, ./bin/www]

  db:
    build: ./mongo
    image: ageapps/docker-chat:mongo
    volumes:
      - ./database:/data # volume in host -> $(pwd)/database
    environment:
      - MONGO_DB_APP_PASSWORD=node
      - MONGO_DB_APP_USERNAME=node
      - MONGO_DB_APP_DATABASE=nodedb
    # volumes:
    #   - ./database:/data # volume in host -> $(pwd)/database
    ports:
      - "27017:27017"    
    healthcheck:
      test: ["CMD", "echo", "show dbs", "|", "mongo"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: mongod --smallfiles

  # rabbit:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "15672:15672"
