kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  # NOTE(ageapps): proxy-protocol doesn´t seem to be supported in GKE
  use-proxy-protocol: "true"
  proxy-send-timeout: "3600"
  proxy-read-timeout: "3600"
  enable-vts-status: "true"
